Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.boot_timeout = 3600 # 60 minutes
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     vb.memory = 4096
     vb.cpus = 7
  end

$provisionscript = <<-HEREDOC
    sudo apt-get update
    sudo apt-get upgrade -y

    # Build tools and Qt5:
    sudo apt-get install -y \
        build-essential \
        qttools5-dev-tools \
        libqt5opengl5-dev \
        libqt5multimedia5-dev \
        libqt5multimedia5-plugins \
        qt5-default

    # Utilities:
    sudo apt-get install -y \
        git \
        vim \
        help2man \
        markdown \
        htop

    sudo apt-get -y install \
        libglew-dev \
        libglu1-mesa-dev \
        liblo-dev \
        liblo-tools \
        libraw1394-dev \
        librtmidi-dev \
        libstk0-dev \
        libxv-dev

    # Destop environment:
    sudo apt-get -y install \
        xubuntu-desktop

    # GStreamer:
    sudo apt-get -y install \
        gstreamer1.0-alsa \
        gstreamer1.0-dev \
        gstreamer1.0-plugins-bad \
        gstreamer1.0-libav \
        gstreamer1.0-vaapi \
        gstreamer1.0-plugins-bad-videoparsers \
        gstreamer1.0-plugins-base \
        gstreamer1.0-plugins-base-apps \
        gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-ugly \
        gstreamer1.0-tools \
        gstreamer1.0-vaapi \
        gstreamer1.0-x
    # Video tools
    sudo apt-get -y install \
        ffmpeg \
        mencoder \
        vlc

    # Ubuntu / Debian packaging tools
    sudo apt-get -y install \
        cdbs \
        git-buildpackage \
        cowbuilder \
        dput

    sudo chown -R vagrant:vagrant /home/vagrant/*
    mkdir -p /home/vagrant/Desktop
    mkdir -p /home/vagrant/src
    cd /home/vagrant/src
    git clone https://github.com/mapmapteam/mapmap.git /home/vagrant/src/mapmap

    # if [ -e /vagrant/id_rsa ]
    # then
    #   sudo cp /vagrant/id_rsa ~/.ssh
    #   sudo cp /vagrant/id_rsa.pub ~/.ssh
    #   sudo cp /vagrant/known_hosts ~/.ssh
    #   eval `ssh-agent -s`
    #   ssh-add ~/.ssh/id_rsa
    #   git clone git@github.com:mapmapteam/mapmap.git ~/src/mapmap
    #   sudo shutdown -h now
    # else
    #   git clone https://github.com/mapmapteam/mapmap.git ~/src/mapmap
    # fi
HEREDOC

  config.vm.provision "shell", inline: $provisionscript, privileged: false
end

